version: "3.9"

services:
  backend:
    container_name: nodejs
    build:
      context: .
    ports:
      - "80:3000"
      - "9229:9229"
    command: tail -f /dev/null
    volumes:
      - ./:/app
      - node_modules:/app/node_modules

volumes:
  node_modules:
